apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Fréquence de récupération des métriques

    scrape_configs:
      - job_name: 'node-redis'
        static_configs:
          - targets: ['192.168.49.2:30804']
