apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
  labels:
    app: node-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          image: amira860/node-redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: redis://redis-master:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis-replicas:6379
          resources:  
            requests: 
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"

